### ISSUE TITLE
Security Concern from the system

### ISSUE THREAD

**Issue by Scarlaid** [Leayal/SnowBreakLauncher-Dotnet#1]
![image](https://github.com/Leayal/SnowBreakLauncher-Dotnet/assets/90851437/47f20354-0305-4be0-9335-2a0b764deacc)

Been getting this issue lately and I dont know why D:

**Comment by Leayal** [comment]
~~I'll look into this issue, frankly speaking, I suspect it's CsWin32's generated code which is not fully compatible with the "beta" .NET SDK.~~
I don't know what triggered this, nor how to even "reproduce" this...
Have you checked if your operating system still in good health/condition?

## Does this happen when running launcher only or it can happen for any applications?
## Does this error message box shown by the launcher itself, or by a security application?
## Can I also ask which launcher version you were running?
- v0.0.1 (which was deleted, it's also the first alpha build)
- v0.0.2 (which was also deleted, still also an alpha build)
- v1.0.0 (which is the current latest one, visible in the Release section)
- Or it's a build-from-source by yourself? If it's this case, can I know which part you changed (if any) or which version of the source.
## And what operating system you were using (when running the launcher)?

**Comment by Leayal** [comment]
In case the operating system's health is in unknown condition, you can perform a quick check by:

Open start and search for "cmd". Then right click on the `Command prompt` and select `run as admin`.
Type `sfc /scannow` in the Command Prompt window and press Enter.
Once its done, type this command in CMD:
`DISM /Online /Cleanup-Image /ScanHealth`
Another one after:
`DISM /Online /Cleanup-Image /RestoreHealth`

Look at the Command Prompt window to see if it reports any problems.
(After all 3 commands are done and reading the command logs, restart your pc).

**Comment by Leayal** [comment]
Can you try the binaries from this re-release and let me know if the issue is fixed or not?
https://github.com/Leayal/SnowBreakLauncher-Dotnet/releases/tag/1.0.0-revised-1

**Comment by Scarlaid** [comment]
That is a lot of question, but anyway
- The prompt only appear when opening this launcher, nothing affected
- I honestly don't know if this was shown by the launcher or the system, because I have never encounter such prompt in my time using this
- When I found this launcher, it was on Pre-release, and it was lanching fine, until the recent update, which just like the provided picture above
- I'm on Windows 11 IoT Enterprise LTSC, if that helps
- Doubtful it was a system health because I reinstalled just a month ago, did it anyway to no avail.

The latest release fixed the issue, surprisingly :D 
![image](https://github.com/Leayal/SnowBreakLauncher-Dotnet/assets/90851437/dbd92316-7d96-4c32-b290-17ac6ff315c8)

**Comment by Leayal** [comment]
> The latest release fixed the issue, surprisingly :D

Then my suspect may be right. It's the preview (worse, old preview version) SDK (which also was reported to have found CVE, iirc). Building the binaries with the oudated SDK lead to that security warning.
I think it's windows things to show that error box.
That's my educated guess anyway.

As for why I used the out-dated version of the SDK, the latest version of .NET 8 SDK (8.0.100-RC1) has compatibility issue with CsWin32 package: The generated code of CsWin32 can't be compiled, and since it's generated code, I can't edit it, either.

Which left me with the only choice, not using latest .NET8 SDK (at least until the issue above is fixed), or going back to .NET7 SDK.
Anyway, since it's fixed, I will close this issue.
