### ISSUE TITLE
Rquesting for Discord RPC, may or may not possible...

### ISSUE THREAD

**Issue by Scarlaid** [Leayal/SnowBreakLauncher-Dotnet#3]
_Been playing others game like Honkai Impact 3 and Star Rail, with RPC (made from the community itself), to a point I have been too used to having a Rich Presence, at least for the profile_

Will there ever be, at least, a rich presence for this game, at least from the launcher, like [Collapse](https://github.com/neon-nyan/Collapse) for every Mihoyo games ever? 

Here are some reference that came to mind for me to ask this, for wider RPC content display:
- [This RPC](https://github.com/Matsko3/Elysia-Rich-Presence) for Star Rail
- [This RPC](https://github.com/Zanzancomms/Genshin-Impact-Rich-Presence-Proof-of-Concept-) for Genshin Impact
> Both use [Tesseract](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.1.20220118.exe)
- [This RPC](https://github.com/mashirochan/HoloCure-DiscordRPC) for Holocure using [YYToolkit](https://github.com/Archie-osu/YYToolkit/releases/latest)

Can't be sure that this would be possible but worth to ask, thanks :D

**Comment by Leayal** [comment]
I'm sorry for letting you down. But I don't think I can make it.

Partially because there is no way to detect the operation the player's doing in-game. (I don't know how to write .dll file mod to export these info from the game to Discord client's RPC, too, even if I knew how to, there's still anti-cheat to worry about loading "unknown" .dll files into the game).
And unlike the two games using Tesseract for parsing texts, this game barely have any texts on the screen regarding dungeon/instance the player's currently in (Once you join, say, a story map or a `neural simulation` battle stage, they're all look the same UI...).

However, if you are referring to simple RPC which displays a static/fixed texts, then I think I can make it. Though this is kinda outside of the scope of this launcher....

**Comment by Scarlaid** [comment]
> Though this is kinda outside of the scope of this launcher....

Damn, I thought this was always almost a thing for game launchers nowadays, because of how much I have been encountering
Overall, good to know, Snowbreak was only 2 months "old" anyway so asking such was too early 

Have a good day.
