### ISSUE TITLE
they changed manifest.json cdn domain format

### ISSUE THREAD

**Issue by LemonPAKA** [Leayal/SnowBreakLauncher-Dotnet#5]
1.8.0's mainfest.json 
Global now is https://snowbreak-dl.amazingseasuncdn.com/118c343979b2407f4a6b3ad2b84d6d79/PC/updates/manifest.json
China Mainland is https://cbjq.xoyocdn.com/118c343979b2407f4a6b3ad2b84d6d79/PC/updates/manifest.json

**Comment by LemonPAKA** [comment]
![QQ截图20240530223409](https://github.com/Leayal/SnowBreakLauncher-Dotnet/assets/17202894/5294d6c1-b9ee-4368-a280-872eac6eb009)
looks like they use this now

**Comment by Leayal** [comment]
They don't just change the URL.
The patching method is also changed. They use binary_diff tool to patch now.

Probably to save download size by downloading only changes and then patching existing files on local disk.
I will fix it when I somehow grasp their patching tool.
Or someone could help me with that.

Until then, the launcher is considered broken and can't be used.
Though I have little free time to spend on this project...

**Comment by LemonPAKA** [comment]
> They don't just change the URL. The patching method is also changed. They use binary_diff tool to patch now.
> 
> Probably to save download size by downloading only changes and then patching existing files on local disk. I will fix it when I somehow grasp their patching tool. Or someone could help me with that.
> 
> Until then, the launcher is considered broken and can't be used. Though I have little free time to spend on this project...

In China Mainland, they start rolling out Seasun game launcher instead of old launcher for new players who download game from offical site. the old one still works.

And looks like Seasun game launcher use different download method?  and new launcher's files download URL is changed from "cbjq.xoyocdn.com" to "cbjq-client.xoyocdn.com".
Seasun game launcher will auto detect where the game file is and break old launcher detection(it will say need update and you will need to download entire game if you open old launcher after used new launcher).

I am not sure will they release that new launcher for global.

**Comment by Leayal** [comment]
I'm not sure, it's actually depending on the publisher that they have different distribution system.
That said, the gist of the global's patching system is:
- There are 4 additional data fields in the manifest.json: `base`, `diff`, `size diff` and `isPrimary`. I kinda figured out the first 3, but still don't know `primary` of exactly what.....
- If global see the file match the `base`'s hash, it will download the `diff` and do binary-patch on the existing file. Otherwise, it will *redownload* the `base` file again to do the binary-patch.
I still need to know what does `primary` field means exactly before rolling out the design that match their system...

I prefer this kind of patching system, though. Less download and still recoverable by redownloading `base` file. Although it will need to use CPU and heavier disk IO quite a bit due to binary patching thingie...

**Comment by Leayal** [comment]
I was wrong.
The old patching system can still usable, but it's somehow break the game if trying to update the existing game, redownload full game may fix that.

The new patching works like:
- If the file doesn't exist, pull latest file from server.
- If the file exist but is multiple versions behind or is damaged/corrupted, also pull latest from server.
- If the file exist and is one version behind, download binary-diff file and perform binary-patch on existing file.

`primary` was simply just a meant to determine whether the file must exact match the hash, or just the existence alone (hash mismatch allowed) is enough.

**Comment by Leayal** [comment]
I will close this issue for now since the launcher is current working with the new patching system.

**Comment by Leayal** [comment]
@LemonPAKA I've updated the launcher codebase. Please checkout the [sample file of the new manifest](https://github.com/Leayal/SnowBreakLauncher-Dotnet/blob/master/docs/publish/v2/launcher-manifest.sample.json). The new launcher will use the json data in the `v2` directory.
